// <auto-generated />
using System;
using System.Text.Json;
using Cato.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cato.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CatoDbContext))]
    [Migration("20260228103150_AddGroupMemberCountSnapshot")]
    partial class AddGroupMemberCountSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cato.Domain.Entities.CcuHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CcuCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PeakCcuToday")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Steam API");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_ccu_history_timestamp");

                    b.HasIndex("GameId", "Timestamp")
                        .HasDatabaseName("idx_ccu_history_game_time");

                    b.HasIndex("GameId", "Timestamp", "Source")
                        .IsUnique()
                        .HasDatabaseName("idx_ccu_history_unique");

                    b.ToTable("ccu_history", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("CapsuleImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailedDescription")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeaderImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsEarlyAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<JsonDocument>("Platforms")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("SteamReviewScore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupportedLanguages")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("DeveloperId");

                    b.HasIndex("GameType");

                    b.HasIndex("PublisherId");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("main_game", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GenreType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GenreName");

                    b.HasIndex("GameId", "GenreName", "Source")
                        .IsUnique();

                    b.ToTable("game_genre", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GenreTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TagName");

                    b.HasIndex("TagType");

                    b.HasIndex("GameId", "TagName")
                        .IsUnique();

                    b.ToTable("genre_tag", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GroupMemberCountSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_group_member_count_date");

                    b.HasIndex("GameId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("unique_group_member_count_snapshot");

                    b.ToTable("group_member_count_snapshot", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .HasDatabaseName("idx_ingestion_log_source");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("idx_ingestion_log_start_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_ingestion_log_status");

                    b.ToTable("ingestion_log", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Name");

                    b.ToTable("legal_entity", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.OwnedGameData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gifts")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodWishlistBalance")
                        .HasColumnType("integer");

                    b.Property<int>("PurchasesAndActivations")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WishlistAdditions")
                        .HasColumnType("integer");

                    b.Property<int>("WishlistDeletions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("owned_game_data", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSaleFinancial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BasePrice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CombinedDiscountId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossReturnsUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("GrossRevenueUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("NetRevenueUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("NetUnits")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("\"SalesUnits\" - \"ReturnsUnits\"", true);

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Steam");

                    b.Property<int>("ReturnsUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("RevenueShareTier")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<string>("SalePrice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SaleType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SalesUnits")
                        .HasColumnType("integer");

                    b.Property<decimal>("SteamCommissionUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TaxUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("idx_steam_sale_country");

                    b.HasIndex("SaleDate")
                        .HasDatabaseName("idx_steam_sale_date");

                    b.HasIndex("GameId", "SaleDate")
                        .HasDatabaseName("idx_steam_sale_game_date");

                    b.HasIndex("GameId", "SaleDate", "CountryCode", "PackageId", "Platform")
                        .IsUnique()
                        .HasDatabaseName("unique_sale_record");

                    b.ToTable("steam_sale_financial", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamTraffic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClickThroughRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer");

                    b.Property<int>("NetWishlistChange")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("\"WishlistAdditions\" - \"WishlistDeletions\"", true);

                    b.Property<decimal>("PurchaseConversionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Purchases")
                        .HasColumnType("integer");

                    b.Property<int>("StorePageVisits")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TrafficDate")
                        .HasColumnType("date");

                    b.Property<string>("TrafficSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("integer");

                    b.Property<int>("WishlistAdditions")
                        .HasColumnType("integer");

                    b.Property<int>("WishlistDeletions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrafficSource")
                        .HasDatabaseName("idx_steam_traffic_source");

                    b.HasIndex("GameId", "TrafficDate")
                        .HasDatabaseName("idx_steam_traffic_game_date");

                    b.HasIndex("GameId", "TrafficDate", "TrafficSource")
                        .IsUnique()
                        .HasDatabaseName("unique_traffic_record");

                    b.ToTable("steam_traffic", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.CcuHistory", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("CcuHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.HasOne("Cato.Domain.Entities.LegalEntity", "Developer")
                        .WithMany("DeveloperGames")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cato.Domain.Entities.LegalEntity", "Publisher")
                        .WithMany("PublisherGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameGenre", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GenreTag", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("Tags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GroupMemberCountSnapshot", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("GroupMemberCountSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.OwnedGameData", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("OwnedGameData")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSaleFinancial", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("SalesFinancials")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamTraffic", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("TrafficRecords")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.Navigation("CcuHistories");

                    b.Navigation("Genres");

                    b.Navigation("GroupMemberCountSnapshots");

                    b.Navigation("OwnedGameData");

                    b.Navigation("SalesFinancials");

                    b.Navigation("Tags");

                    b.Navigation("TrafficRecords");
                });

            modelBuilder.Entity("Cato.Domain.Entities.LegalEntity", b =>
                {
                    b.Navigation("DeveloperGames");

                    b.Navigation("PublisherGames");
                });
#pragma warning restore 612, 618
        }
    }
}
