// <auto-generated />
using System;
using System.Text.Json;
using Cato.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cato.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CatoDbContext))]
    [Migration("20260704125652_AddSteamSpecialEvents")]
    partial class AddSteamSpecialEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cato.Domain.Entities.ActionImpact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BaselineConversionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("BaselineEnd")
                        .HasColumnType("date");

                    b.Property<decimal?>("BaselineRevenueUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("BaselineSalesUnits")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("BaselineStart")
                        .HasColumnType("date");

                    b.Property<int?>("BaselineTraffic")
                        .HasColumnType("integer");

                    b.Property<int?>("BaselineWishlistAdds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("ConversionRateChange")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("MeasurementEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MeasurementStart")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("ResultConversionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ResultRevenueUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("ResultSalesUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("ResultTraffic")
                        .HasColumnType("integer");

                    b.Property<int?>("ResultWishlistAdds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RevenueChangePercent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("RevenueChangeUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("Roi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("SalesChangePercent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SalesUnitsChange")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalCostUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("TrafficChange")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TrafficChangePercent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("WishlistChange")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WishlistChangePercent")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .IsUnique()
                        .HasDatabaseName("unique_action_impact");

                    b.HasIndex("Roi")
                        .HasDatabaseName("idx_action_impact_roi");

                    b.ToTable("action_impact", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.ActionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliverableUrl")
                        .HasColumnType("text");

                    b.Property<int?>("Engagement")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("OutreachDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ResponseDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Planned");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("idx_action_target_action");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_action_target_status");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("idx_action_target_target");

                    b.HasIndex("ActionId", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("unique_action_target");

                    b.ToTable("action_target", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.ActiveUsersHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dau")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mau")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("idx_active_users_history_recorded_at");

                    b.HasIndex("GameId", "RecordedAt")
                        .IsUnique()
                        .HasDatabaseName("unique_active_users_history");

                    b.ToTable("active_users_history", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.AppChangeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<long>("ChangeNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "ChangeNumber")
                        .HasDatabaseName("idx_app_change_record_app_change");

                    b.HasIndex("AppId", "DetectedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_app_change_record_app_detected");

                    b.HasIndex("GameId", "DetectedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_app_change_record_game_detected");

                    b.ToTable("app_change_record", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.AppKeyValueSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ChangeNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawKeyValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("idx_app_kv_snapshot_appid");

                    b.HasIndex("GameId");

                    b.HasIndex("AppId", "ChangeNumber")
                        .IsUnique()
                        .HasDatabaseName("unique_app_kv_snapshot");

                    b.ToTable("app_kv_snapshot", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.CcuHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CcuCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PeakCcuToday")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Steam API");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_ccu_history_timestamp");

                    b.HasIndex("GameId", "Timestamp")
                        .HasDatabaseName("idx_ccu_history_game_time");

                    b.HasIndex("GameId", "Timestamp", "Source")
                        .IsUnique()
                        .HasDatabaseName("idx_ccu_history_unique");

                    b.ToTable("ccu_history", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.DemoDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DemoAppId")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GeoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("SharePercent")
                        .HasColumnType("decimal(6,3)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<long>("TotalDownloads")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_demo_download_snapshot_date");

                    b.HasIndex("GameId", "SnapshotDate", "GeoType", "GeoName")
                        .IsUnique()
                        .HasDatabaseName("unique_demo_download");

                    b.ToTable("demo_download", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("CapsuleImageUrl")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("ContentDescriptorIds")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailedDescription")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<string>("FilterReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FilteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeaderImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsEarlyAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFiltered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<JsonDocument>("Platforms")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("SteamReviewScore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupportedLanguages")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("DeveloperId");

                    b.HasIndex("GameType");

                    b.HasIndex("PublisherId");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("IsFiltered", "FilterReason");

                    b.ToTable("main_game", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameAchievementSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<string>("IconGrayUrl")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("idx_game_achievement_schema_appid");

                    b.HasIndex("GameId", "ApiName")
                        .IsUnique()
                        .HasDatabaseName("unique_game_achievement_schema_game_api");

                    b.ToTable("game_achievement_schema", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Primary");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("idx_game_action_action");

                    b.HasIndex("GameId")
                        .HasDatabaseName("idx_game_action_game");

                    b.HasIndex("ActionId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("unique_game_action");

                    b.ToTable("game_action", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GenreType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GenreName");

                    b.HasIndex("GameId", "GenreName", "Source")
                        .IsUnique();

                    b.ToTable("game_genre", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameNews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Contents")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FeedLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("idx_game_news_published_at");

                    b.HasIndex("GameId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("unique_game_news");

                    b.ToTable("game_news", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GenreTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TagName");

                    b.HasIndex("TagType");

                    b.HasIndex("GameId", "TagName")
                        .IsUnique();

                    b.ToTable("genre_tag", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GroupMemberCountSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_group_member_count_date");

                    b.HasIndex("GameId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("unique_group_member_count_snapshot");

                    b.ToTable("group_member_count_snapshot", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .HasDatabaseName("idx_ingestion_log_source");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("idx_ingestion_log_start_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_ingestion_log_status");

                    b.ToTable("ingestion_log", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("cato-backend");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .HasDatabaseName("idx_job_run_job_name");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("idx_job_run_start_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_job_run_status");

                    b.HasIndex("JobName", "StartTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_job_run_job_started");

                    b.ToTable("job_run", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Name");

                    b.ToTable("legal_entity", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.MarketingAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ActionDate")
                        .HasColumnType("date");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ActualCostUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("BudgetUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DecisionSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Planned");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionDate")
                        .HasDatabaseName("idx_action_date");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("idx_action_type");

                    b.HasIndex("PlannedDate")
                        .HasDatabaseName("idx_action_planned_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_action_status");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.MarketingTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudienceRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("AudienceSize")
                        .HasColumnType("integer");

                    b.Property<string>("ContactDiscord")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactTwitter")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("CostEstimateUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("LastContacted")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<JsonDocument>("PreferredGenres")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("PreferredTags")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("ResponseRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_marketing_target_name");

                    b.HasIndex("Platform")
                        .HasDatabaseName("idx_marketing_target_platform");

                    b.HasIndex("TargetType")
                        .HasDatabaseName("idx_marketing_target_type");

                    b.ToTable("marketing_target", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.OwnedGameData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gifts")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodWishlistBalance")
                        .HasColumnType("integer");

                    b.Property<int>("PurchasesAndActivations")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WishlistAdditions")
                        .HasColumnType("integer");

                    b.Property<int>("WishlistDeletions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("owned_game_data", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePriceUsd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPriceUsd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("idx_price_snapshot_captured_at");

                    b.HasIndex("GameId", "CapturedAt", "Currency")
                        .IsUnique()
                        .HasDatabaseName("unique_price_snapshot");

                    b.ToTable("price_snapshot", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.ReviewSummarySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewScore")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewScoreDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalNegative")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPositive")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_review_summary_snapshot_date");

                    b.HasIndex("GameId", "SnapshotDate")
                        .HasDatabaseName("idx_review_summary_game_date");

                    b.ToTable("review_summary_snapshot", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamDbSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Follows")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Price")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Rating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Release")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SevenDayGain")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_steamdb_snapshot_date");

                    b.HasIndex("Source")
                        .HasDatabaseName("idx_steamdb_snapshot_source");

                    b.HasIndex("GameId", "SnapshotDate", "Source")
                        .IsUnique()
                        .HasDatabaseName("unique_steamdb_snapshot");

                    b.ToTable("steamdb_snapshot", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamPlayerAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameAchievementSchemaId")
                        .HasColumnType("uuid");

                    b.Property<long>("SteamId64")
                        .HasColumnType("bigint");

                    b.Property<long>("UnlockTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameAchievementSchemaId")
                        .HasDatabaseName("idx_steam_player_achievement_schema");

                    b.HasIndex("SteamId64", "GameAchievementSchemaId")
                        .IsUnique()
                        .HasDatabaseName("unique_steam_player_achievement_player_schema");

                    b.ToTable("steam_player_achievement", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamPlayerAchievementFetch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AchievedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("QuarantinedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SchemaCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SteamId64")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastFetchedAt")
                        .HasDatabaseName("idx_steam_player_achievement_fetch_last");

                    b.HasIndex("QuarantinedUntil")
                        .HasDatabaseName("idx_steam_player_achievement_fetch_quarantine");

                    b.HasIndex("SteamId64", "AppId")
                        .IsUnique()
                        .HasDatabaseName("unique_steam_player_achievement_fetch_pair");

                    b.ToTable("steam_player_achievement_fetch", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamPlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarFullUrl")
                        .HasColumnType("text");

                    b.Property<string>("AvatarHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CommunityVisibilityState")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLogoff")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LocCityId")
                        .HasColumnType("integer");

                    b.Property<string>("LocCountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("LocStateCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PersonaState")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonaStateFlags")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryClanId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ProfileState")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<string>("RealName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("SteamId64")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommunityVisibilityState")
                        .HasDatabaseName("idx_steam_player_profile_visibility");

                    b.HasIndex("LastFetchedAt")
                        .HasDatabaseName("idx_steam_player_profile_last_fetched");

                    b.HasIndex("SteamId64")
                        .IsUnique()
                        .HasDatabaseName("unique_steam_player_profile_steamid");

                    b.ToTable("steam_player_profile", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievementsComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AuthorAchievementsAtReview")
                        .HasColumnType("integer");

                    b.Property<long?>("AuthorSteamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GameAchievementCountAtFetch")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PlaytimeAtReviewMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PlaytimeForeverMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("ReceivedForFree")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SteamPurchase")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimestampUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VotedUp")
                        .HasColumnType("boolean");

                    b.Property<int>("VotesFunny")
                        .HasColumnType("integer");

                    b.Property<int>("VotesUp")
                        .HasColumnType("integer");

                    b.Property<bool>("WrittenDuringEarlyAccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuthorSteamId")
                        .HasDatabaseName("idx_steam_review_author_steamid");

                    b.HasIndex("Language")
                        .HasDatabaseName("idx_steam_review_language");

                    b.HasIndex("GameId", "RecommendationId")
                        .IsUnique()
                        .HasDatabaseName("unique_steam_review_game_rec");

                    b.HasIndex("GameId", "TimestampCreated")
                        .HasDatabaseName("idx_steam_review_game_created");

                    b.ToTable("steam_review", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSaleFinancial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BasePrice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CombinedDiscountId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossReturnsUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("GrossRevenueUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("NetRevenueUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("NetUnits")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("\"SalesUnits\" - \"ReturnsUnits\"", true);

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Steam");

                    b.Property<int>("ReturnsUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("RevenueShareTier")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<string>("SalePrice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SaleType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SalesUnits")
                        .HasColumnType("integer");

                    b.Property<decimal>("SteamCommissionUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TaxUsd")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("idx_steam_sale_country");

                    b.HasIndex("SaleDate")
                        .HasDatabaseName("idx_steam_sale_date");

                    b.HasIndex("GameId", "SaleDate")
                        .HasDatabaseName("idx_steam_sale_game_date");

                    b.HasIndex("GameId", "SaleDate", "CountryCode", "PackageId", "Platform")
                        .IsUnique()
                        .HasDatabaseName("unique_sale_record");

                    b.ToTable("steam_sale_financial", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSpecialEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnnouncementGid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CapsuleImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("ClanAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("EventUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HeaderImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SaleVanityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<JsonDocument>("TabNames")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementGid")
                        .IsUnique()
                        .HasDatabaseName("unique_steam_special_event_gid");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_steam_special_event_last_seen");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("idx_steam_special_event_start");

                    b.ToTable("steam_special_event", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSpecialEventGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SteamDisplayedEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SteamDisplayedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SteamSpecialEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_steam_special_event_game_last_seen");

                    b.HasIndex("SteamSpecialEventId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("unique_steam_special_event_game");

                    b.ToTable("steam_special_event_game", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamTraffic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClickThroughRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer");

                    b.Property<int>("NetWishlistChange")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("\"WishlistAdditions\" - \"WishlistDeletions\"", true);

                    b.Property<decimal>("PurchaseConversionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Purchases")
                        .HasColumnType("integer");

                    b.Property<int>("StorePageVisits")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TrafficDate")
                        .HasColumnType("date");

                    b.Property<string>("TrafficSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("integer");

                    b.Property<int>("WishlistAdditions")
                        .HasColumnType("integer");

                    b.Property<int>("WishlistDeletions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrafficSource")
                        .HasDatabaseName("idx_steam_traffic_source");

                    b.HasIndex("GameId", "TrafficDate")
                        .HasDatabaseName("idx_steam_traffic_game_date");

                    b.HasIndex("GameId", "TrafficDate", "TrafficSource")
                        .IsUnique()
                        .HasDatabaseName("unique_traffic_record");

                    b.ToTable("steam_traffic", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamTrafficBreakdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("PageCategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PageFeature")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<long>("Visits")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "SnapshotDate", "PageCategory", "PageFeature")
                        .IsUnique()
                        .HasDatabaseName("unique_traffic_breakdown");

                    b.ToTable("steam_traffic_breakdown", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.TargetMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GenreMatchScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HistoricalPerformanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LifecycleStage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("MatchingGenres")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("MatchingTags")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("RelevanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TagMatchScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("idx_target_match_game");

                    b.HasIndex("RelevanceScore")
                        .HasDatabaseName("idx_target_match_score");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("idx_target_match_target");

                    b.HasIndex("GameId", "TargetId", "LifecycleStage")
                        .IsUnique()
                        .HasDatabaseName("unique_target_match");

                    b.ToTable("target_match", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.WishlistInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CopiesSold")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("LinkScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RelatedAppId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "SnapshotDate", "RelatedAppId")
                        .IsUnique()
                        .HasDatabaseName("unique_wishlist_insight");

                    b.ToTable("wishlist_insight", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.ActionImpact", b =>
                {
                    b.HasOne("Cato.Domain.Entities.MarketingAction", "Action")
                        .WithOne("Impact")
                        .HasForeignKey("Cato.Domain.Entities.ActionImpact", "ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Cato.Domain.Entities.ActionTarget", b =>
                {
                    b.HasOne("Cato.Domain.Entities.MarketingAction", "Action")
                        .WithMany("ActionTargets")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cato.Domain.Entities.MarketingTarget", "Target")
                        .WithMany("ActionTargets")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Cato.Domain.Entities.ActiveUsersHistory", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("ActiveUsersHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.AppChangeRecord", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("AppChangeRecords")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.AppKeyValueSnapshot", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("AppKeyValueSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.CcuHistory", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("CcuHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.DemoDownload", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("DemoDownloads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.HasOne("Cato.Domain.Entities.LegalEntity", "Developer")
                        .WithMany("DeveloperGames")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cato.Domain.Entities.LegalEntity", "Publisher")
                        .WithMany("PublisherGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameAchievementSchema", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("AchievementSchemas")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameAction", b =>
                {
                    b.HasOne("Cato.Domain.Entities.MarketingAction", "Action")
                        .WithMany("GameActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("GameActions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameGenre", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameNews", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("News")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GenreTag", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("Tags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GroupMemberCountSnapshot", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("GroupMemberCountSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.OwnedGameData", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("OwnedGameData")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.ReviewSummarySnapshot", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("ReviewSummarySnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamDbSnapshot", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("SteamDbSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamPlayerAchievement", b =>
                {
                    b.HasOne("Cato.Domain.Entities.GameAchievementSchema", "GameAchievementSchema")
                        .WithMany("PlayerAchievements")
                        .HasForeignKey("GameAchievementSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameAchievementSchema");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamReview", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("SteamReviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSaleFinancial", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("SalesFinancials")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSpecialEventGame", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("SteamSpecialEventGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cato.Domain.Entities.SteamSpecialEvent", "SteamSpecialEvent")
                        .WithMany("Games")
                        .HasForeignKey("SteamSpecialEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SteamSpecialEvent");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamTraffic", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("TrafficRecords")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamTrafficBreakdown", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("TrafficBreakdowns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.TargetMatch", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("TargetMatches")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cato.Domain.Entities.MarketingTarget", "Target")
                        .WithMany("TargetMatches")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Cato.Domain.Entities.WishlistInsight", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("WishlistInsights")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.Navigation("AchievementSchemas");

                    b.Navigation("ActiveUsersHistories");

                    b.Navigation("AppChangeRecords");

                    b.Navigation("AppKeyValueSnapshots");

                    b.Navigation("CcuHistories");

                    b.Navigation("DemoDownloads");

                    b.Navigation("GameActions");

                    b.Navigation("Genres");

                    b.Navigation("GroupMemberCountSnapshots");

                    b.Navigation("News");

                    b.Navigation("OwnedGameData");

                    b.Navigation("PriceSnapshots");

                    b.Navigation("ReviewSummarySnapshots");

                    b.Navigation("SalesFinancials");

                    b.Navigation("SteamDbSnapshots");

                    b.Navigation("SteamReviews");

                    b.Navigation("SteamSpecialEventGames");

                    b.Navigation("Tags");

                    b.Navigation("TargetMatches");

                    b.Navigation("TrafficBreakdowns");

                    b.Navigation("TrafficRecords");

                    b.Navigation("WishlistInsights");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameAchievementSchema", b =>
                {
                    b.Navigation("PlayerAchievements");
                });

            modelBuilder.Entity("Cato.Domain.Entities.LegalEntity", b =>
                {
                    b.Navigation("DeveloperGames");

                    b.Navigation("PublisherGames");
                });

            modelBuilder.Entity("Cato.Domain.Entities.MarketingAction", b =>
                {
                    b.Navigation("ActionTargets");

                    b.Navigation("GameActions");

                    b.Navigation("Impact");
                });

            modelBuilder.Entity("Cato.Domain.Entities.MarketingTarget", b =>
                {
                    b.Navigation("ActionTargets");

                    b.Navigation("TargetMatches");
                });

            modelBuilder.Entity("Cato.Domain.Entities.SteamSpecialEvent", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
