// <auto-generated />
using System;
using System.Text.Json;
using Cato.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cato.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CatoDbContext))]
    [Migration("20260211170744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("CapsuleImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailedDescription")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeaderImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsEarlyAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<JsonDocument>("Platforms")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("SteamReviewScore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupportedLanguages")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("DeveloperId");

                    b.HasIndex("GameType");

                    b.HasIndex("PublisherId");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("main_game", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GenreType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GenreName");

                    b.HasIndex("GameId", "GenreName", "Source")
                        .IsUnique();

                    b.ToTable("game_genre", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.GenreTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TagName");

                    b.HasIndex("TagType");

                    b.HasIndex("GameId", "TagName")
                        .IsUnique();

                    b.ToTable("genre_tag", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Name");

                    b.ToTable("legal_entity", (string)null);
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.HasOne("Cato.Domain.Entities.LegalEntity", "Developer")
                        .WithMany("DeveloperGames")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cato.Domain.Entities.LegalEntity", "Publisher")
                        .WithMany("PublisherGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GameGenre", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.GenreTag", b =>
                {
                    b.HasOne("Cato.Domain.Entities.Game", "Game")
                        .WithMany("Tags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Cato.Domain.Entities.Game", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Cato.Domain.Entities.LegalEntity", b =>
                {
                    b.Navigation("DeveloperGames");

                    b.Navigation("PublisherGames");
                });
#pragma warning restore 612, 618
        }
    }
}
